In [1]:
from am4894pd.utils import df_dummy_ts # used to generate some dummy data
from am4894plots.plots import plot_lines, plot_lines_grid
from am4894plots.lines.bokeh import plot_lines as plot_lines_bokeh
from am4894plots.lines.bokeh import plot_lines_grid as plot_lines_grid_bk

# generate some dummy time series data
df = df_dummy_ts(n_cols=100, freq='1min')
print(df.shape)
display(df.head())

(1342, 100)

,col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,...,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99
time,,,,,,,,,,,,,,,,,,,,,
2019-01-01 01:39:00,-0.041540,-0.015640,-0.088465,0.100661,0.306903,0.149670,0.000200,0.099670,0.042768,0.055602,...,0.165216,-0.094995,0.138635,0.062686,-0.041191,-0.036014,-0.013742,-0.045490,0.024800,-0.097677
2019-01-01 01:40:00,-0.033604,-0.006791,-0.078170,0.110704,0.290986,0.129016,-0.005323,0.104015,0.022830,0.044616,...,0.160148,-0.075158,0.151227,0.056134,-0.020128,-0.060546,-0.004432,-0.005034,0.021618,-0.092262
2019-01-01 01:41:00,-0.059194,-0.009444,-0.093377,0.117194,0.298986,0.115362,-0.020550,0.105631,0.016626,0.028865,...,0.165131,-0.067776,0.152930,0.050811,-0.026136,-0.061639,0.015497,-0.003261,0.001974,-0.087266
2019-01-01 01:42:00,-0.072171,-0.002628,-0.077317,0.104989,0.298667,0.106731,-0.006038,0.111628,-0.009640,0.019633,...,0.168907,-0.094582,0.152691,0.043514,-0.014356,-0.079048,0.035660,0.001078,-0.005674,-0.068539
2019-01-01 01:43:00,-0.049739,0.020355,-0.054416,0.091260,0.282364,0.106448,-0.011635,0.100433,-0.023989,0.009771,...,0.175941,-0.096083,0.151412,0.057118,0.008902,-0.100618,0.024052,-0.015245,-0.004177,-0.068052

In [2]:
# make shaded region
shade_regions = [(df.index[-100:].min(), df.index.max(), 'yellow')]
print(shade_regions)

[(Timestamp('2019-01-01 22:21:00'), Timestamp('2019-01-02 00:00:00'), 'yellow')]

In [3]:
# plot each time series on single plot as a line
plot_lines_grid(
    df, return_p=False, show_p=False, out_path='dev/dev.html', h_each=100, w=1200, legend=False, yaxes_visible=False,
    shade_regions=shade_regions
)