In [1]:
from am4894pd.utils import df_dummy_ts # used to generate some dummy data
from am4894plots.plots import plot_lines, plot_lines_grid
from am4894plots.lines.bokeh import plot_lines as plot_lines_bokeh
from am4894plots.lines.bokeh import plot_lines_grid as plot_lines_grid_bk

# generate some dummy time series data
df = df_dummy_ts(n_cols=100, freq='1min')
print(df.shape)
display(df.head())

(1342, 100)

,col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,...,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99
time,,,,,,,,,,,,,,,,,,,,,
2019-01-01 01:39:00,0.077032,-0.092871,-0.010932,0.012813,0.047485,0.201153,0.054963,-0.006001,-0.004654,0.128477,...,0.196954,-0.070047,-0.124432,-0.198009,0.009010,-0.014799,-0.000066,-0.083944,0.139674,0.123472
2019-01-01 01:40:00,0.101084,-0.101554,-0.031297,0.049490,0.057729,0.193194,0.067910,-0.016196,-0.011731,0.124561,...,0.188638,-0.068893,-0.131333,-0.206166,0.026500,-0.010065,0.007182,-0.090142,0.150411,0.136986
2019-01-01 01:41:00,0.100856,-0.089283,-0.041479,0.058809,0.065864,0.241950,0.080679,-0.007007,-0.016415,0.123621,...,0.181403,-0.061397,-0.126606,-0.184990,0.061352,-0.029728,0.035754,-0.091131,0.160579,0.158696
2019-01-01 01:42:00,0.085332,-0.082130,-0.029519,0.056328,0.057999,0.243612,0.075409,-0.011697,-0.010893,0.132844,...,0.162695,-0.057509,-0.104842,-0.185817,0.028684,-0.063903,0.042163,-0.083455,0.170615,0.168981
2019-01-01 01:43:00,0.104361,-0.096472,-0.033772,0.051332,0.023342,0.252449,0.076437,-0.028797,-0.004384,0.123803,...,0.143436,-0.103357,-0.116836,-0.177169,0.024584,-0.074287,0.046060,-0.095825,0.152068,0.167669

In [2]:
# make shaded region
shade_regions = [
    (df.index[-300:].min(), df.index[-101], 'lightblue'),
    (df.index[-100:].min(), df.index.max(), 'yellow')
]
print(shade_regions)

[(Timestamp('2019-01-01 19:01:00'), Timestamp('2019-01-01 22:20:00'), 'lightblue'), (Timestamp('2019-01-01 22:21:00'), Timestamp('2019-01-02 00:00:00'), 'yellow')]

In [3]:
subplot_titles = [f'blah blah blah blah blah blah - {col}' for col in df.columns]

In [4]:
# plot each time series on single plot as a line
plot_lines_grid(
    df, subplot_titles=subplot_titles, return_p=False, show_p=False, out_path='example_plots/big_grid.html', h_each=100, w=1200, 
    legend=False, yaxes_visible=False, shade_regions=shade_regions, text_position='bottom right', xaxes_visible=False
)